CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  firstname varchar(50),
  lastname varchar(50)
);

CREATE TABLE migrations (
  filename text NOT NULL UNIQUE PRIMARY KEY,
  applied_at timestamp with time zone DEFAULT now()
);